#
# CONFIG FILE FOR SKLEARN-BASED
#     SYMBOLIC ML MODELING          
#
# Author   : Filippo Arcadu
# Date     : 09/11/2018



###############################
#                             # 
#             MODEL           #
#                             #
###############################

model:
    # Algorithm name, choose among [ 'class' , 'regr' ]
    algorithm: class   

    # Metric to select best model, choose among [ 'accuracy' , 'r2' , 'auc' , 'cohen_kappa' ]
    metric: auc

    # Output variable
    col_out: NUMEX-BINARY

    # Feature columns to select
    # Provide the column names individually as a list, e.g. [ 'col_name_01' , 'col_name_02' ]
    # or specify a substring common to all column names to select, e.g. '*pattern*''
    select: None

    # Feature columns to exclude
    # Provide the column names individually as a list, e.g. [ 'col_name_01' , 'col_name_02' ]
    # or specify a substring common to all column names to exclude, e.g. '*pattern*'
    exclude: ['NUMEX']



###############################
#                             # 
#          VALIDATION         #
#                             #
###############################

validation:
    # Data percentage for testing
    testing: 20

    # Name of the column constraining the fold splitting
    col_constr: ANONID

    # Select type of cross-validation, choose among [ None , k-fold , resampling ]
    cv_type: k-fold

    # How many folds
    n_folds: 5



###############################
#                             # 
#            PARAMS           #
#                             #
###############################

params:
    # Loss function
    # for classification             --> Logloss , CrossEntropy
    # for multi-class classification --> MultiClass , MultiClassOneVsAll
    # for regression                 --> MAE , MAPE , Quantile , RMSE , LogLinQuantile
    loss_function: Logloss

    # Iterations, i.e. max number of trees that can be built
    iterations: '4:16:2'

    # Learning rate
    learning_rate: 0.3

    # L2 regularization coefficient (any positive number allowed)
    l2_leaf_reg: 3

    # Type of bootstrap, choose amng Bayesian, Bernoulli, No
    bootstrap_type: Bayesian

    # Depth of the tree , max number is 16
    depth: 2

    # Random subspace method, i.e. percentage of features to use at each split selection, value in (0,1]
    rsm: 1

    # Leaf estimation method, choose between Gradient, Newton
    leaf_estimation_method: Gradient

    # Boosting scheme, choose between Ordered, Plain, Ordered works better for small datasets but it's slower
    boosting_type: Ordered

    # Random strength, i.e. score the standard deviation multiplier, use this param to avoid overfitting
    random_strength: 1

    # Number of threads; if -1, it uses all threads
    thread_count: 1


